"""added cascade delete on relationship

Revision ID: 570fc7e79d49
Revises: f8d3ac239365
Create Date: 2025-02-11 21:56:51.445957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570fc7e79d49'
down_revision: Union[str, None] = 'f8d3ac239365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
