"""Add user_name and overtime to UserHour

Revision ID: 63fe0f7eb4d8
Revises: eabba83beffa
Create Date: 2025-04-09 19:24:06.543267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fe0f7eb4d8'
down_revision: Union[str, None] = 'eabba83beffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
