"""Add user_name and overtime to UserHour

Revision ID: eabba83beffa
Revises: d44036a963b1
Create Date: 2025-04-09 19:23:36.751278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabba83beffa'
down_revision: Union[str, None] = 'd44036a963b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_hours', sa.Column('user_name', sa.VARCHAR(length=255), nullable=False))
    op.add_column('users_hours', sa.Column('overtime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_hours', 'overtime')
    op.drop_column('users_hours', 'user_name')
    # ### end Alembic commands ###
