"""changed models

Revision ID: f9bc497cba95
Revises: 570fc7e79d49
Create Date: 2025-02-11 22:55:11.761856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9bc497cba95'
down_revision: Union[str, None] = '570fc7e79d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teams_user_id_fkey', 'teams', type_='foreignkey')
    op.drop_column('teams', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teams_user_id_fkey', 'teams', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
